# CIS 443-01 - Analytics Programming
## Program 1
__Due__: Monday September 23 (by 11:59 PM)<br />
__Worth__: 50 pts.<br />
__Purpose__: Use a function and repetition control structure to demonstrate compounding interest.

### Directions
In the code cell below, write Python code to accomplish the following using what you've learned through Chapter 4. 


#### Part 1

Your code should allow the user to enter three values: a principle balance, an interest rate, and a number of years. 

For simplicity's sake, we will compound our interest once per year. In order to do so, create a function interest_calculator with three inputs, corresponding to the user inputs. They should have the default values 10000, .09, and 10, respectively. 

Your formula to calculate the interest will be Balance(Year + 1) = Balance * (1 + interest rate)

So for example, starting with 10,000 and a 5% interest rate, the formula is 10,000 * (1 + .05) = 10,500. The next year would be 10,500 * (1 + .05) = 11,025 and so on. 

Each year you will output the year number, and the value of the balance that year.

In [25]:
# Put Program 1 Code Here. Do not create any additional code blocks or points may be deducted. 

principle_bal = float(input("Enter the principle balance"))
int_rate = float(input("Enter the interest rate: "))
years = int(input("Enter the number of years: "))

def interest_calculator(bal, intrate, years):

    for year in range(1, years + 1):
        bal = bal * (1 + intrate)
        print("Year: ", year, "compounded value is", round(bal,2))
    
interest_calculator(principle_bal, int_rate, years)

Enter the principle balance 7500
Enter the interest rate:  0.05
Enter the number of years:  200

Year:  1 compounded value is 7875.0
Year:  2 compounded value is 8268.75
Year:  3 compounded value is 8682.19
Year:  4 compounded value is 9116.3
Year:  5 compounded value is 9572.11
Year:  6 compounded value is 10050.72
Year:  7 compounded value is 10553.25
Year:  8 compounded value is 11080.92
Year:  9 compounded value is 11634.96
Year:  10 compounded value is 12216.71
Year:  11 compounded value is 12827.55
Year:  12 compounded value is 13468.92
Year:  13 compounded value is 14142.37
Year:  14 compounded value is 14849.49
Year:  15 compounded value is 15591.96
Year:  16 compounded value is 16371.56
Year:  17 compounded value is 17190.14
Year:  18 compounded value is 18049.64
Year:  19 compounded value is 18952.13
Year:  20 compounded value is 19899.73
Year:  21 compounded value is 20894.72
Year:  22 compounded value is 21939.46
Year:  23 compounded value is 23036.43
Year:  24 compounded value is 24188.25
Year:  25 compounded value is 25397.66
Year:  26 compounded value is 26667.55
Year:  27 compounded value is 28000.92
Year:  28 compounded value is 29400.97
Year:  29 compounded value is 30871.02
Year:  30 compounded value is 32414.57
Year:  31 compounded value is 34035.3
Year:  32 compounded value is 35737.06
Year:  33 compounded value is 37523.91
Year:  34 compounded value is 39400.11
Year:  35 compounded value is 41370.12
Year:  36 compounded value is 43438.62
Year:  37 compounded value is 45610.55
Year:  38 compounded value is 47891.08
Year:  39 compounded value is 50285.63
Year:  40 compounded value is 52799.92
Year:  41 compounded value is 55439.91
Year:  42 compounded value is 58211.91
Year:  43 compounded value is 61122.5
Year:  44 compounded value is 64178.63
Year:  45 compounded value is 67387.56
Year:  46 compounded value is 70756.94
Year:  47 compounded value is 74294.78
Year:  48 compounded value is 78009.52
Year:  49 compounded value is 81910.0
Year:  50 compounded value is 86005.5
Year:  51 compounded value is 90305.77
Year:  52 compounded value is 94821.06
Year:  53 compounded value is 99562.12
Year:  54 compounded value is 104540.22
Year:  55 compounded value is 109767.23
Year:  56 compounded value is 115255.59
Year:  57 compounded value is 121018.37
Year:  58 compounded value is 127069.29
Year:  59 compounded value is 133422.76
Year:  60 compounded value is 140093.89
Year:  61 compounded value is 147098.59
Year:  62 compounded value is 154453.52
Year:  63 compounded value is 162176.19
Year:  64 compounded value is 170285.0
Year:  65 compounded value is 178799.25
Year:  66 compounded value is 187739.22
Year:  67 compounded value is 197126.18
Year:  68 compounded value is 206982.49
Year:  69 compounded value is 217331.61
Year:  70 compounded value is 228198.19
Year:  71 compounded value is 239608.1
Year:  72 compounded value is 251588.51
Year:  73 compounded value is 264167.93
Year:  74 compounded value is 277376.33
Year:  75 compounded value is 291245.14
Year:  76 compounded value is 305807.4
Year:  77 compounded value is 321097.77
Year:  78 compounded value is 337152.66
Year:  79 compounded value is 354010.29
Year:  80 compounded value is 371710.81
Year:  81 compounded value is 390296.35
Year:  82 compounded value is 409811.17
Year:  83 compounded value is 430301.72
Year:  84 compounded value is 451816.81
Year:  85 compounded value is 474407.65
Year:  86 compounded value is 498128.03
Year:  87 compounded value is 523034.44
Year:  88 compounded value is 549186.16
Year:  89 compounded value is 576645.46
Year:  90 compounded value is 605477.74
Year:  91 compounded value is 635751.62
Year:  92 compounded value is 667539.21
Year:  93 compounded value is 700916.17
Year:  94 compounded value is 735961.97
Year:  95 compounded value is 772760.07
Year:  96 compounded value is 811398.08
Year:  97 compounded value is 851967.98
Year:  98 compounded value is 894566.38
Year:  99 compounded value is 939294.7
Year:  100 compounded value is 986259.43
Year:  101 compounded value is 1035572.41
Year:  102 compounded value is 1087351.03
Year:  103 compounded value is 1141718.58
Year:  104 compounded value is 1198804.51
Year:  105 compounded value is 1258744.73
Year:  106 compounded value is 1321681.97
Year:  107 compounded value is 1387766.07
Year:  108 compounded value is 1457154.37
Year:  109 compounded value is 1530012.09
Year:  110 compounded value is 1606512.69
Year:  111 compounded value is 1686838.33
Year:  112 compounded value is 1771180.24
Year:  113 compounded value is 1859739.26
Year:  114 compounded value is 1952726.22
Year:  115 compounded value is 2050362.53
Year:  116 compounded value is 2152880.66
Year:  117 compounded value is 2260524.69
Year:  118 compounded value is 2373550.92
Year:  119 compounded value is 2492228.47
Year:  120 compounded value is 2616839.89
Year:  121 compounded value is 2747681.89
Year:  122 compounded value is 2885065.98
Year:  123 compounded value is 3029319.28
Year:  124 compounded value is 3180785.24
Year:  125 compounded value is 3339824.51
Year:  126 compounded value is 3506815.73
Year:  127 compounded value is 3682156.52
Year:  128 compounded value is 3866264.34
Year:  129 compounded value is 4059577.56
Year:  130 compounded value is 4262556.44
Year:  131 compounded value is 4475684.26
Year:  132 compounded value is 4699468.48
Year:  133 compounded value is 4934441.9
Year:  134 compounded value is 5181163.99
Year:  135 compounded value is 5440222.19
Year:  136 compounded value is 5712233.3
Year:  137 compounded value is 5997844.97
Year:  138 compounded value is 6297737.22
Year:  139 compounded value is 6612624.08
Year:  140 compounded value is 6943255.28
Year:  141 compounded value is 7290418.05
Year:  142 compounded value is 7654938.95
Year:  143 compounded value is 8037685.9
Year:  144 compounded value is 8439570.19
Year:  145 compounded value is 8861548.7
Year:  146 compounded value is 9304626.13
Year:  147 compounded value is 9769857.44
Year:  148 compounded value is 10258350.31
Year:  149 compounded value is 10771267.83
Year:  150 compounded value is 11309831.22
Year:  151 compounded value is 11875322.78
Year:  152 compounded value is 12469088.92
Year:  153 compounded value is 13092543.37
Year:  154 compounded value is 13747170.53
Year:  155 compounded value is 14434529.06
Year:  156 compounded value is 15156255.51
Year:  157 compounded value is 15914068.29
Year:  158 compounded value is 16709771.7
Year:  159 compounded value is 17545260.29
Year:  160 compounded value is 18422523.3
Year:  161 compounded value is 19343649.47
Year:  162 compounded value is 20310831.94
Year:  163 compounded value is 21326373.54
Year:  164 compounded value is 22392692.22
Year:  165 compounded value is 23512326.83
Year:  166 compounded value is 24687943.17
Year:  167 compounded value is 25922340.33
Year:  168 compounded value is 27218457.34
Year:  169 compounded value is 28579380.21
Year:  170 compounded value is 30008349.22
Year:  171 compounded value is 31508766.68
Year:  172 compounded value is 33084205.02
Year:  173 compounded value is 34738415.27
Year:  174 compounded value is 36475336.03
Year:  175 compounded value is 38299102.83
Year:  176 compounded value is 40214057.98
Year:  177 compounded value is 42224760.87
Year:  178 compounded value is 44335998.92
Year:  179 compounded value is 46552798.86
Year:  180 compounded value is 48880438.81
Year:  181 compounded value is 51324460.75
Year:  182 compounded value is 53890683.78
Year:  183 compounded value is 56585217.97
Year:  184 compounded value is 59414478.87
Year:  185 compounded value is 62385202.82
Year:  186 compounded value is 65504462.96
Year:  187 compounded value is 68779686.11
Year:  188 compounded value is 72218670.41
Year:  189 compounded value is 75829603.93
Year:  190 compounded value is 79621084.13
Year:  191 compounded value is 83602138.33
Year:  192 compounded value is 87782245.25
Year:  193 compounded value is 92171357.51
Year:  194 compounded value is 96779925.39
Year:  195 compounded value is 101618921.66
Year:  196 compounded value is 106699867.74
Year:  197 compounded value is 112034861.13
Year:  198 compounded value is 117636604.18
Year:  199 compounded value is 123518434.39
Year:  200 compounded value is 129694356.11

### Example Output
<div class="alert alert-block alert-info">
Enter the principle balance:  14339<br>
Enter the interest rate:  .11<br>
Enter the number of years:  10<br>
Year 1 compounded value is \$15916.29<br>
Year 2 compounded value is \$17667.08<br>
Year 3 compounded value is \$19610.46<br>
Year 4 compounded value is \$21767.61<br>
Year 5 compounded value is \$24162.05<br>
Year 6 compounded value is \$26819.87<br>
Year 7 compounded value is \$29770.06<br>
Year 8 compounded value is \$33044.77<br>
Year 9 compounded value is \$36679.69<br>
Year 10 compounded value is \$40714.46
</div>

#### Part 2
**Answer the following**:

How many years of this calculation do you have to use before you first get 38,000, at 5% interest, starting with 7,500?<br />
34 years
<br />
100,000?<br />
54 years <br />
1,000,000?<br />
101 years<br />

Double click the cell in Jupyter to edit (__5 pts.__)

Be sure to save and exit your Jupyter Notebook and Shutdown Jupyter Lab (from the __File__ menu) before you submit your notebook on Blackboard for grading.